// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB91NhqzNnRYC54evVIPAzYD57MH-WVoqE',
    appId: '1:484117876550:web:287b41a483a7b6a6f51f47',
    messagingSenderId: '484117876550',
    projectId: 'spotifyclonexyx',
    authDomain: 'spotifyclonexyx.firebaseapp.com',
    storageBucket: 'spotifyclonexyx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUMIzNXmnYFnIUebe6C8r8vjKfiRNpxY0',
    appId: '1:484117876550:android:f2174af9deea1ccdf51f47',
    messagingSenderId: '484117876550',
    projectId: 'spotifyclonexyx',
    storageBucket: 'spotifyclonexyx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZLHWy_7xnZnjvGCO2nKnOEVhsZIDzXPw',
    appId: '1:484117876550:ios:276474513e6c9a38f51f47',
    messagingSenderId: '484117876550',
    projectId: 'spotifyclonexyx',
    storageBucket: 'spotifyclonexyx.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZLHWy_7xnZnjvGCO2nKnOEVhsZIDzXPw',
    appId: '1:484117876550:ios:276474513e6c9a38f51f47',
    messagingSenderId: '484117876550',
    projectId: 'spotifyclonexyx',
    storageBucket: 'spotifyclonexyx.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB91NhqzNnRYC54evVIPAzYD57MH-WVoqE',
    appId: '1:484117876550:web:4ea27e811d783c8af51f47',
    messagingSenderId: '484117876550',
    projectId: 'spotifyclonexyx',
    authDomain: 'spotifyclonexyx.firebaseapp.com',
    storageBucket: 'spotifyclonexyx.firebasestorage.app',
  );

}